version: '3.7'

services:
  delta_core:
    container_name: delta_core_pro
    image: deltareporter/delta_core:latest
    environment:
      - APP_SETTINGS=config.ProductionConfig
      - DATABASE_URL=postgresql://delta:123123@db/delta_db
      - WEBSOCKETS_URL=http://delta_websockets:8080/send_event
    ports:
      - '5000:5000'
    restart: on-failure
    links:
      - db
      - delta_websockets
    depends_on:
      - db
    command: sh -c "python manage.py db upgrade && gunicorn -b 0.0.0.0:5000 app:app"

  delta_websockets:
    container_name: delta_websockets_pro
    image: deltareporter/delta_websockets:latest
    environment:
      - APP_SETTINGS=config.ProductionConfig
    ports:
      - '8080:8080'
    restart: on-failure

  delta_frontend:
    container_name: delta_frontend_pro
    image: deltareporter/delta_frontend:latest
    ports:
      - '3000:3000'
    environment:
      - DELTA_CORE_URL=http://delta_core:5000
      - PUBLIC_DELTA_CORE_URL=http://localhost:5000
      - PUBLIC_DELTA_WEBSOCKETS_URL=http://localhost:8080
      - PORT=3000
    links:
      - delta_core

  db:
      image: "postgres:12"
      container_name: delta_database_pro
      environment:
        - POSTGRES_USER=delta
        - POSTGRES_PASSWORD=123123
        - POSTGRES_DB=delta_db
      ports:
        - '54320:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U delta -d delta_db"]
        interval: 10s
        timeout: 5s
        retries: 5
