# Markdown https://www.mkdocs.org/user-guide/writing-your-docs/

# Project information
site_name: Delta Reporter
site_description: Next generation reporting tool where results from all kind all tests are displayed in real time
site_author: Juan Negrier & Oleksandra Pishcheiko
site_url: https://deltareporter.org/

# Repository
repo_name: delta-reporter/delta-reporter
repo_url: https://github.com/delta-reporter/delta-reporter

# Copyright
copyright: Copyright &copy;  2022 Juan Negrier & Oleksandra Pishcheiko

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: delta_logo
  favicon: assets/favicon.png
  features:
     - instant
     - tabs
     - navigation.tabs
     - navigation.tabs.sticky
  custom_dir: docs/home_override

nav:
    - 'home.md'
    - Documentation:
      - 'index.md'
      - 'structure.md'
      - 'main_features.md'
      - 'start_guide.md'
      - Deploying Delta:
        - 'dev_deployment.md'
        - 'deployment.md'
      - Plugins:
        - 'webdriverIO.md'
        - 'testNG.md'
        - 'phpUnit.md'
        - cypress.md
        - jest.md
        - junit.md
        - python.md 
      - 'cicd.md'
      - 'troubleshooting.md'
      - 'contributing.md'
