version: '3.7'

services:
  delta_core:
    container_name: delta_core_dev
    build:
      context: ${HOME}/delta-local/delta-core
      dockerfile: Dockerfile
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://delta:123123@db/delta_db
      - WEBSOCKETS_URL=http://delta_websockets:8080/send_event
    volumes:
      - '${HOME}/delta-local/delta-core:/app'
    ports:
      - '5000:5000'
    restart: on-failure
    links:
      - db
      - delta_websockets
    depends_on:
      - db

  delta_websockets:
    container_name: delta_websockets_dev
    build:
      context: ${HOME}/delta-local/delta-websockets
      dockerfile: Dockerfile
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
    volumes:
      - '${HOME}/delta-local/delta-websockets:/app'
    ports:
      - '8080:8080'
    restart: on-failure

  delta_frontend:
    container_name: delta_frontend_dev
    build:
      context: ${HOME}/delta-local/delta-frontend
      dockerfile: Dockerfile
    volumes:
      - '${HOME}/delta-local/delta-frontend:/app'
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      - NODE_ENV=development
      - DELTA_CORE_URL=http://delta_core:5000
      - PUBLIC_DELTA_CORE_URL=http://localhost:5000
      - PUBLIC_DELTA_WEBSOCKETS_URL=http://localhost:8080
    links:
      - delta_core

  db:
      image: "postgres:12"
      container_name: delta_database_dev
      environment:
        - POSTGRES_USER=delta
        - POSTGRES_PASSWORD=123123
        - POSTGRES_DB=delta_db
      ports:
        - '54320:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U delta -d delta_db"]
        interval: 10s
        timeout: 5s
        retries: 5
