version: '3.7'

services:
  delta_core:
    container_name: delta_core_dev
    build:
      context: ${HOME}/delta-local/delta-core
      dockerfile: Dockerfile
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://delta:123123@db/delta_db
      - DAYS_OLD_MEDIA_DELETE=3
      - REDIS_URL=redis://redis:6379/0
      - BROKER_URL=amqp://delta:123123@rabbit//
    volumes:
      - '${HOME}/delta-local/delta-core:/app'
    command: sh start_dev.sh
    ports:
      - '5000:5000'
    restart: on-failure
    links:
      - db
    depends_on:
      - db

  delta_worker:
    container_name: delta_worker_dev
    build:
      context: ${HOME}/delta-local/delta-core
      dockerfile: Dockerfile
    environment:
      - APP_SETTINGS=config.ProductionConfig
      - DATABASE_URL=postgresql://delta:123123@db/delta_db
      - REDIS_URL=redis://redis:6379/0
      - BROKER_URL=amqp://delta:123123@rabbit//
    volumes:
      - '${HOME}/delta-local/delta-core:/app'
    restart: on-failure
    links:
      - redis
      - rabbit
    depends_on:
      - rabbit
    command: sh -c "python -m celery -A tasks worker --loglevel INFO"

  delta_frontend:
    container_name: delta_frontend_dev
    build:
      context: ${HOME}/delta-local/delta-frontend
      dockerfile: Dockerfile
    volumes:
      - '${HOME}/delta-local/delta-frontend:/app'
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      - NODE_ENV=development
      - DELTA_CORE_URL=http://delta_core:5000
      - PUBLIC_DELTA_CORE_URL=http://localhost:5000
    links:
      - delta_core

  db:
      image: postgres:12
      container_name: delta_database_dev
      environment:
        - POSTGRES_USER=delta
        - POSTGRES_PASSWORD=123123
        - POSTGRES_DB=delta_db
      ports:
        - '54320:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U delta -d delta_db"]
        interval: 10s
        timeout: 5s
        retries: 5

  redis:
    image: redis:6.2
    hostname: redis

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.8
    environment:
      - RABBITMQ_DEFAULT_USER=delta
      - RABBITMQ_DEFAULT_PASS=123123
